name: Select Module Build

on:
  workflow_dispatch:
    inputs:
      selected_module:
        description: 'Select module to build'
        required: true
        default: 'Module1'
        options:
          - 'Module1'
          - 'Module2'
          - 'Module3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Selected Module
        run: echo "Building ${{ github.event.inputs.selected_module }}"

