name: Select Module Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Select Module
        id: module
        run: |
          echo "::set-output name=selected_module::$(echo -e "Module1\nModule2\nModule3" | fzf)"
      
      - name: Build Selected Module
        run: echo "Building ${{ steps.module.outputs.selected_module }}"
